apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: acrfiaprodrigoborges.azurecr.io/tc-rodrigo-fiap-microservice-users:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: ConnectionStrings__Main
          valueFrom:
            secretKeyRef:
              name: user-secrets
        - name: AuthKey
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: AuthKey
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: Jwt__Key
        - name: Jwt__Issuer
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: Jwt__Issuer
        - name: Jwt__Audience
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: Jwt__Audience
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: LoadBalancer # Cria um IP público para acesso externo
  selector:
    app: users-service
  ports:
  - port: 80
    targetPort: 8080
---
# Requisito de HPA (Auto Scaling)
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: users-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50